### ISSUE TITLE
error rendering *head (raw view) on Unicorn+Nginx

### ISSUE THREAD

**Issue by ChanceDoor** [wagn/wagn#493]
it shows on the top:"error rendering *head (raw view)"
and lost css

**Comment by ethn** [comment]
Is there anything useful in the log file?

**Comment by ChanceDoor** [comment]
127.0.0.1:11211 failed (count: 2) Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 11211

DalliError: No server available

**Comment by ChanceDoor** [comment]
I commented the dalli line, no error log.but in browser, there are errors: 
http://xxx.xxx.com/files/~1526/7935.css Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found) http://xxx.xxx.com/files/~1528/7938.js Failed to load resource: the server

**Comment by ethn** [comment]
I'm surprised there's not more than that in the log file (at `(deck root)/log/(environment).log`).

Usually that error means there was a problem generating the optimized css and js files.  It's interesting, though, that those links above make it look like the files were generated.

Without log info, it's going to be tricky to diagnose, but I would make sure your permissions are set up so that the webserver process can write to the files directory.  That's a common snag.
