### ISSUE TITLE
Change log ?

### ISSUE THREAD

**Issue by jmatsushita** [wagn/wagn#517]
Hi there,

Would be great to have a changelog regarding minor releases. I'm on 1.16.3 and don't know how to decide if I should update to 1.16.7

Cheers,

Jun

**Comment by ethn** [comment]
Yes, we should add that, particularly when there have been so many minor changes; it's hard to get a sense of what's going on from the commit log.

The biggest changes recently involve file handling and card queries.  The former involved new upload interface, and the latter makes things faster, but otherwise most of the improvements are behind-the-scenes.

**Comment by xithan** [comment]
We started to use github's release log feature: https://github.com/wagn/wagn/releases
